global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'headscale'
    static_configs:
      - targets: ['172.20.0.20:9090']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
