server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "67199c6c762f9bcc8f6e06c5f9b615a0"
  cookie_secure: false
  cookie_same_site: "lax"
  cookie_http_only: true

headscale:
  url: "http://172.20.0.20:8080"
  api_key: ""
  config_strict: false
  timeout: "30s"

auth:
  type: "api_key"

database:
  type: "memory"

logging:
  level: "info"

features:
  enable_registration: false
  enable_machine_approval: true
  enable_route_approval: true
