# Alternative: Change server_url instead
server_url: https://headscale.internal
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false

database:
  type: postgres
  postgres:
    host: postgres
    port: 5432
    name: headscale
    user: headscale
    pass: changeme123
    ssl_mode: disable

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default

dns:
  magic_dns: true
  base_domain: tailnet.work
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8

policy:
  mode: file
  path: /etc/headscale/acl.yaml

log:
  level: info

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
